# Unique project identifier
sonar.projectKey=transcriber-app
sonar.projectName=Transcriber AI Platform
sonar.projectVersion=1.0

# Path to the source code
sonar.sources=services, scripts
# Path to tests (if you have a tests folder)
# sonar.tests=tests

# Language specific settings
sonar.language=py
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

# Exclude directories that aren't source code
sonar.exclusions=venv/**, .git/**, **/node_modules/**, infrastructure/**, **/__pycache__/**

# Quality Gate settings
sonar.qualitygate.wait=true