services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: ../../services/api
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy # This ensures redis is fully ready first
    volumes:
      - ../../uploads:/app/uploads

  worker:
    build: ../../services/worker
    environment:
      - PYTHONPATH=/app
      - RQ_REDIS_URL=redis://redis:6379  # This talks to the CLI
      - REDIS_HOST=redis                 # This can be used by your code
      - HF_HOME=/models/cache
    depends_on:
      redis:
        condition: service_healthy # This ensures redis is fully ready first
    volumes:
      - ../../uploads:/app/uploads
      - whisper_models:/models

  frontend:
    build: ../../services/frontend
    env_file:
    - ../../services/frontend/.env.docker
    depends_on:
      - api
# The Master Gateway
  gateway:
    image: nginx:latest
    ports:
      - "80:80" # This is now the ONLY port exposed to your computer
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - frontend
      
volumes:
  whisper_models: