{
 "title": "API Traffic (RPS)",
 "description": "Requests Per Second",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active AI Workers (KEDA)",
   "type": "timeseries",
   "description": "track the worker deployment to see KEDA scaling it from 0 up to 1 (or more) when a video hits the Redis queue, and back to 0 when it finishes",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"worker\", namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, handler) (rate(http_request_duration_seconds_bucket{handler!=\"/metrics\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Traffic (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total{handler!=\"/metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}